package com.shuaiqiu.fuckets100

import android.util.Log

object AnswerHtmlGenerator {
    
    private const val TAG = "AnswerHtmlGenerator"
    
    fun generatePaperHtml(paper: ETS100AnswerReader.Paper, isDarkMode: Boolean): String {
        Log.d(TAG, "Generate HTML: ${paper.title}, dark: $isDarkMode")
        
        val bgColor = if (isDarkMode) "#1a1a1a" else "#f5f5f5"
        val cardBgColor = if (isDarkMode) "#2d2d2d" else "#ffffff"
        val textColor = if (isDarkMode) "#e0e0e0" else "#333333"
        val subTextColor = if (isDarkMode) "#a0a0a0" else "#666666"
        val accentColor = "#007AFF"
        val answerColor = "#34C759"
        
        val html = StringBuilder()
        
        html.append("""
            <!DOCTYPE html>
            <html>
            <head>
                <meta charset="UTF-8">
                <meta name="viewport" content="width=device-width, initial-scale=1.0">
                <style>
                    * { box-sizing: border-box; margin: 0; padding: 0; }
                    body {
                        font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
                        background-color: $bgColor;
                        color: $textColor;
                        padding: 16px;
                        line-height: 1.6;
                    }
                    .paper-title {
                        font-size: 20px;
                        font-weight: bold;
                        text-align: center;
                        margin-bottom: 20px;
                        padding: 16px;
                        background: $cardBgColor;
                        border-radius: 12px;
                        color: $accentColor;
                    }
                    .section {
                        margin-bottom: 24px;
                        background: $cardBgColor;
                        border-radius: 12px;
                        padding: 16px;
                    }
                    .section-title {
                        font-size: 16px;
                        font-weight: 600;
                        color: $accentColor;
                        margin-bottom: 12px;
                        padding-bottom: 8px;
                        border-bottom: 2px solid ${accentColor}40;
                    }
                    .question {
                        margin-bottom: 16px;
                        padding: 12px;
                        background: ${if (isDarkMode) "#3d3d3d" else "#fafafa"};
                        border-radius: 8px;
                    }
                    .q-header {
                        display: flex;
                        justify-content: space-between;
                        align-items: center;
                        margin-bottom: 8px;
                    }
                    .q-num { font-weight: bold; color: $accentColor; font-size: 14px; }
                    .q-answer { color: $answerColor; font-weight: bold; font-size: 14px; }
                    .q-content { color: $subTextColor; font-size: 13px; margin-bottom: 4px; }
                    .q-choices { margin-top: 8px; }
                    .choice-item { padding: 4px 8px; margin: 2px 0; font-size: 13px; color: $subTextColor; }
                    .choice-item.correct { color: $answerColor; font-weight: bold; }
                    .footer { text-align: center; margin-top: 24px; padding: 16px; color: $subTextColor; font-size: 12px; }
                </style>
            </head>
            <body>
        """.trimIndent())
        
        html.append("""<div class="paper-title">${escapeHtml(paper.title)}</div>""")
        
        for (section in paper.sections) {
            if (section.questions.isEmpty()) continue
            html.append("""
                <div class="section">
                    <div class="section-title">${escapeHtml(section.title)}</div>
            """.trimIndent())
            for (question in section.questions) {
                html.append(generateQuestionHtml(question, isDarkMode))
            }
            html.append("""</div>""")
        }
        
        html.append("""
            <div class="footer">
                Generated by Fe - ${getCurrentTime()}
            </div>
            </body>
            </html>
        """.trimIndent())
        
        Log.d(TAG, "HTML generated, length: ${html.length}")
        return html.toString()
    }
    
    private fun generateQuestionHtml(question: ETS100AnswerReader.Question, isDarkMode: Boolean): String {
        val content = when (val c = question.content) {
            is ETS100AnswerReader.AnswerContent.Reading -> c.text
            is ETS100AnswerReader.AnswerContent.Choice -> {
                c.items.joinToString("<br>") { item ->
                    val opts = item.options.mapIndexed { idx, opt -> "${('A'.code + idx).toChar()}. ${escapeHtml(opt)}" }.joinToString("<br>")
                    "${escapeHtml(item.question)}<br>$opts"
                }
            }
            is ETS100AnswerReader.AnswerContent.QATuple -> c.pairs.joinToString("<br>") { "Q: ${it.question}<br>A: ${it.answer}" }
        }
        
        val answerDisplay = if (question.answer.isNotEmpty()) question.answer else "No answer"
        
        val choicesHtml = if (question.content is ETS100AnswerReader.AnswerContent.Choice) {
            val items = (question.content as ETS100AnswerReader.AnswerContent.Choice).items
            val correctOption = question.answer.uppercase()
            items.mapIndexed { index, item ->
                val optionLetter = ('A'.code + index).toChar().toString()
                val isCorrect = optionLetter == correctOption
                item.options.mapIndexed { optIdx, optText ->
                    val optLetter = ('A'.code + optIdx).toChar().toString()
                    val isCorrectOpt = isCorrect && optIdx == 0
                    """<div class="choice-item ${if (isCorrectOpt) "correct" else ""}">$optLetter. ${escapeHtml(optText)}</div>"""
                }.joinToString("")
            }.joinToString("")
        } else ""
        
        return """
            <div class="question">
                <div class="q-header">
                    <span class="q-num">Q${question.order}</span>
                    <span class="q-answer">Answer: ${escapeHtml(answerDisplay)}</span>
                </div>
                ${if (content.isNotEmpty()) """<div class="q-content">$content</div>""" else ""}
                ${if (choicesHtml.isNotEmpty()) """<div class="q-choices">$choicesHtml</div>""" else ""}
            </div>
        """.trimIndent()
    }
    
    private fun escapeHtml(text: String): String {
        return text
            .replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace("\"", "&quot;")
            .replace("'", "&#39;")
            .replace("\n", "<br>")
    }
    
    private fun getCurrentTime(): String {
        val sdf = java.text.SimpleDateFormat("yyyy-MM-dd HH:mm", java.util.Locale.getDefault())
        return sdf.format(java.util.Date())
    }
}